"use client"

import Image from "next/image";
import { Inter } from "next/font/google";
import "../app/globals.css";
import { useEffect, useRef, useState } from "react";
import axios from "axios";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FacultyFlow | LARVA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const hiddenFileInput = useRef(null);

  const handleChange = event => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];

      const drive = async () => {        
        const response = await fetch('/api/drive', {
          method: 'POST',
          body: i,
          headers: {
            'Content-Type': i.type,
            "name": i.name,
            "id": children.id
          },
        });
    
        const res = await response.json();
      }
  
      drive();
    }
  };

  return (
    // <form onSubmit={addEntry()}>
    <div>
        <label for="file-upload" class="inline-block rounded-md ml-2 duration-250 text-xs bg-peela text-gray-700 cursor-pointer hover:bg-amber-400">
            <input id="file-upload" type="file" name="filename" class="hidden" ref={hiddenFileInput}
                  onChange={handleChange} />
            <span>Upload</span>
        </label>
    </div>
    // </form>
  );
}