
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "FacultyFlow | LARVA",
//   description: "Generated by create next app",
// };

export default function RootLayout({ id, arrival }) {
  return (
    <div className="shadow-md w-[45vw] h-[18vh] bg-off-white flex rounded-medium text-gray-700 hover:bg-gray-100 m-4">
        <h2>{id } is the id</h2>
        <h2>{arrival}is the arrival date</h2>
    </div>
  );
}
